### ISSUE TITLE
Drop support for some Python version

### ISSUE THREAD

**Issue by menegazzo** [menegazzo/travispy#26]
Keep only the "official" versions: 2.7, 3.4 and pypy

**Comment by nicoddemus** [comment]
I would say `2.7`, `3.4`, `pypy` and the new `3.5`. :smile:

**Comment by jayvdb** [comment]
I'm a big fan of dropping 2.6 support, but just FYI RedHat Enterprise Linux has a heavily patched 2.6 (which is why my main project has to keep 2.6 support).

fwiw, builds are currently broken again because of related changes to the travispy repos.  So if you're going to change this, could you finish it and get the tests working again, please ;-)
My change to get green builds is: https://github.com/jayvdb/travispy/commit/4143aca213aa0fca21b997b9719c5bd2b5e5cab4

**Comment by menegazzo** [comment]
Python 2.6, 3.2 and 3.3 are no longer supported.
